#! /bin/bash

_cli_bash_autocomplete() {
     local cur prev opts base
     COMPREPLY=()
     cur="${COMP_WORDS[COMP_CWORD]}"
     prev="${COMP_WORDS[COMP_CWORD-1]}"
     opts=$( _CLI_SHELL_COMPLETION=true ${COMP_WORDS[@]:0:$COMP_CWORD} )
     stdopts=$( echo $opts | grep '$stdcomp=' | sed -n 's/\$stdcomp=//p' )
     COMPREPLY=( $(compgen $stdopts -W "${opts}" -- ${cur}) )
     return 0
 }
  
 complete -F _cli_bash_autocomplete $PROG
